### ISSUE TITLE
Double deletion in CDllList

### ISSUE THREAD

**Issue by ad3154** [rusoku/canal2#1]
There's a double deletion in `CDllList::RemoveNode` here:

![image](https://github.com/rusoku/canal2/assets/10929341/54f0e787-db9a-4b0f-91b5-f3c4e496812e)

Which causes debug heap validation to fail:

![image](https://github.com/rusoku/canal2/assets/10929341/2b258a50-50b9-4b58-b19f-5a24d444c0d9)

It should be noted though that deleting a `void *` is not really ideal:

![image](https://github.com/rusoku/canal2/assets/10929341/7f12957b-9dc4-454a-95cc-12c4ad0e7ffe)

I would maybe suggest templating this list, or specializing it to deal with `canalMsg *` to avoid this, but perhaps less important than not double deleting. `std::deque` may also suit your needs.

**Comment by rusoku** [comment]
Definitely need to redesign this doublelist algorithm
